voisit-asr = VoisIT talegenkendelse
voisit-asr-description = Talegenkendelse for færøsk
voisit-asr-links-0 = VoisIt talegenkendelse (på færøsk)
voisit-asr-links-1 = VoisIT
voisit-asr-links-2 = VoisIT
sprotin = Sprotin online ordbøger
sprotin-description = Online ordbøger for færøsk
sprotin-links-0 = Sprotin
fao-korp = Korp for færøsk
fao-korp-description = På Korp for færøsk kan du søge i færøske tekster. Tekstkorpusset er grammatisk annoteret.
fao-korp-links-0 = Korp for færøsk
fid = Færøsk bøjningsdatabase
fid-description = Den færøske bøjningsdatabase er en hjemmeside, hvor du kan søge efter færøske ord og se deres bøjninger. Bøjningsmønstrene i den færøske bøjningdatabase er i mange tilfælde langt mere detaljerede end bøjningsmønstrene på Sprotin.
fid-links-0 = Færøske bøjninger
browser-asr = Færøsk talegenkender for webbrowser (beta)
browser-asr-description = Optag direkte fra din browser, upload en lydfil, eller indsæt et link for at få værktøjet til talegenkendelse til at transskribere det, der bliver sagt.
browser-asr-links-0 = Færøsk talegenkendelse (beta)
dictus-asr = Dictus talegenkendelse
dictus-asr-description = Dette program kan skrive det, du siger, ned på Windows-computere. Du kan arbejde i for eksempel Word, Outlook eller på en hjemmeside og lade programmet skrive for dig.
dictus-asr-links-0 = Dictus talegenkendelse
