fao-voisit-asr = VoisIT talegenkendelse
fao-voisit-asr-description = Appen forstår færøsk tale og forsøger at transkribere teksten på skærmen ved hjælp af kunstig intelligens. Resultatet er afhængig af hvor klar talen er, kvaliteten af mikrofonen, og mængden af baggrundsstøj – opmærksomhed omkring disse faktorer er derfor vigtigt.
fao-voisit-asr-links-0 = VoisIt talegenkendelse (på færøsk)
fao-voisit-asr-links-1 = VoisIT
fao-voisit-asr-links-2 = VoisIT
fao-sprotin = Sprotin online ordbøger
fao-sprotin-description = Online ordbøger for færøsk
fao-sprotin-links-0 = Sprotin
fao-korp = Korp for færøsk
fao-korp-description = På Korp for færøsk kan du søge i færøske tekster. Tekstkorpusset er grammatisk annoteret.
fao-korp-links-0 = Korp for færøsk
fao-fid = Færøsk bøjningsdatabase
fao-fid-description = Den færøske bøjningsdatabase er en hjemmeside, hvor du kan søge efter færøske ord og se deres bøjninger. Bøjningsmønstrene i den færøske bøjningdatabase er i mange tilfælde langt mere detaljerede end bøjningsmønstrene på Sprotin.
fao-fid-links-0 = Færøske bøjninger
fao-browser-asr = Færøsk talegenkender for webbrowser (beta)
fao-browser-asr-description = Optag direkte fra din browser, upload en lydfil, eller indsæt et link for at få værktøjet til talegenkendelse til at transskribere det, der bliver sagt.
fao-browser-asr-links-0 = Færøsk talegenkendelse (beta)
fao-dictus-asr = Dictus talegenkendelse
fao-dictus-asr-description = Dette program kan skrive det, du siger, ned på Windows-computere. Du kan arbejde i for eksempel Word, Outlook eller på en hjemmeside og lade programmet skrive for dig.
fao-dictus-asr-links-0 = Dictus talegenkendelse
fao-stavseting = Færøsk Retskrivningsordbog
fao-stavseting-description = Den Færøske Retskrivningsordbog er en autoriseret ordbog med generelle færøske retskrivningsregler. Den har også bøjningsmønstre for de fleste ord.
fao-stavseting-links-0 = Retskrivningsordbog
fao-foenmt = Færøsk-engelsk oversætter (Huggingface)
fao-foenmt-description = En oversættelsesmodel (FO-EN), som bliver udviklet på Færøernes universitet.
fao-foenmt-links-0 = Færøsk-engelsk oversætter
fao-foen-ms-mt = Færøsk maskinoversættelse (Bing)
fao-foen-ms-mt-description = En maskinoversætter fra Microsoft. Den oversætter både fra færøsk og til færøsk.
fao-foen-ms-mt-links-0 = Oversæt til færøsk
fao-foen-ms-mt-links-1 = Oversæt fra færøsk
fao-malradid = Ordlister fra det færøsk Sprogråd
fao-malradid-description = Søg på de online ordlister, som det færøske Sprogråd har på sin hjemmeside.
fao-malradid-links-0 = Sprogrådets ordlister
fao-online-speller = Online færøsk stavekontrol
fao-online-speller-description = Online færøsk stavekontrol: indsæt din tekst og få den rettet.
fao-online-speller-links-0 = Online færøsk stavekontrol
