kal-martha-tts = Talesyntesen Martha
kal-martha-tts-description = Talesyntese for grønlandsk.
kal-martha-tts-links-0 = Martha TTS (på engelsk)
kal-martha-tts-links-1 = Martha TTS (på grønlandsk)
kal-martha-tts-links-2 = Martha TTS (på dansk)
kal-dictionaries = Grønlandske Ordbøger
kal-dictionaries-description = Grønlandske Ordbøger på net
kal-dictionaries-links-0 = Grønlandske Ordbøger
kal-learngrl = Learn Greenlandic
kal-learngrl-description = Learn Greenlandic af Per Langgård.
kal-learngrl-links-0 = Learn Greenlandic
kal-online-speller = Online grønlandsk stavekontrol
kal-online-speller-description = Online stavekontrol for grønlandsk: indsæt din tekst og få den rettet.
kal-online-speller-links-0 = Online grønlandsk stavekontrol
