sme-nds-nob = NDS for nordsamisk ⇔ bokmål
sme-nds-nob-description = Neahttadigisánit — nettordboka mellom nordsamisk og bokmål
sme-nds-nob-more-info = NDS — Neahttadigisánit — for nordsamisk og bokmål inneheld omkring 33 000 oppslagsord i begge retningar.
sme-nds-nob-links-0 = NDS Nordsamisk Bokmål
sme-nds-fin = NDS for nordsamisk ⇔ finsk
sme-nds-fin-description = Neahttadigisánit — nettordboka mellom nordsamisk og finsk
sme-nds-fin-more-info = NDS — Neahttadigisánit — for  nordsamisk og finsk inneheld omkring 11 000 oppslagsord i begge retningar.
sme-nds-fin-links-0 = NDS Nordsamisk Finsk
sme-nds-smn = NDS for nordsamisk ⇔ enaresamisk
sme-nds-smn-description = Neahttadigisánit — nettordboka mellom nordsamisk og enaresamisk
sme-nds-smn-more-info = NDS — Neahttadigisánit — for  nordsamisk og enaresamisk inneheld omsetjingar i begge retningar.
sme-nds-smn-links-0 = NDS Davvi Anár
sme-nds-spa = NDS for nordsamisk ⇐ spansk
sme-nds-spa-description = Neahttadigisánit — nettordboka frå spansk til nordsamisk
sme-nds-spa-more-info = NDS — Neahttadigisánit — frå spansk til nordsamisk inneheld omsetjingar berre i ei retning inntil vidare.
sme-nds-spa-links-0 = NDS Spansk Nordsamisk
sme-jounivest = Jouni A Vest: Suomi–Saame
sme-jounivest-description = Nettordbok mellom nordsamisk og finsk
sme-jounivest-more-info = Enkel HTML-ordbok frå finsk til nordsamisk. Innhaldet er alt på ei side, og du søkjer med søkjefunksjonen i nettlesaren din.
sme-jounivest-links-0 = Jouni Vest Suomi Saame
sme-juridisk = Juridisk termliste
sme-juridisk-description = Liste på nett med juridiske termar på nordsamisk, bokmål og finsk.
sme-juridisk-more-info = Enkelt søkjegrensesnitt for ei liste med ikring 1600 juridiske termar.
sme-juridisk-links-0 = Justermar
sme-korp = Korp for nordsamisk
sme-korp-description = I Korp for nordsamisk kan du søkja i nordsamiske tekstar. Tekstkorpuset er grammatisk annotert.
sme-korp-links-0 = Korp for nordsamisk
sme-oahpa = Oahpa for nordsamisk
sme-oahpa-description = Lær deg nordsamisk med mange ulike øvingar.
sme-oahpa-links-0 = Oahpa Davvi
mtsme = Maskinomsetjing for nordsamisk
mtsme-description = Maskinomsetjing frå nordsamisk til bokmål, med hjelp av Apertium. Resultatet kan bli grammatisk forbetra av ChatGPT, med risk for at innhaldet endrast.
mtsme-links-0 = MT for nordsamisk
sme-online-speller = Nordsamisk stavekontroll på nett
sme-online-speller-description = Nettstavekontroll for nordsamisk: lim inn teksten din og få han retta.
sme-online-speller-links-0 = Nordsamisk nettstavekontroll
