[[paths]]
    reference = "resources/en/mul-resources.ftl"
    l10n = "resources/{locale}/mul-resources.ftl"
    locales = [
        "en",
        "fi",
        "nb",
        "se",
        "sme",
        "smj",
        "sv"
    ]