[[paths]]
    reference = "resources/en/sme-resources.ftl"
    l10n = "resources/{locale}/sme-resources.ftl"
    locales = [
        "en",
        "fi",
        "nb",
        "nn",
        "sme",
        "sv"
    ]