[[paths]]
    reference = "en/mul-resources.ftl"
    l10n = "{locale}/mul-resources.ftl"
    locales = [
        "fi",
        "nb",
        "nn",
        "se",
        "sma",
        "smj",
        "sv",
        "fo", 
        "kl", 
        "fkv", 
    ]