sje-nds = Pitesamisk NDS
sje-nds-description = Pitesamiske ordboksressurser
sje-nds-more-info = Pitesamisk nähttadigibáhko (NDS). Ordbøker mellom pitesamisk og andre språk og motsatt.
sje-nds-links-0 = Pitesamisk NDS
sje-sjelex = Pitesamisk ordbok
sje-sjelex-description = Pitesamisk leksikalsk database
sje-sjelex-more-info = Den pitesamiske leksikalske databasen på nett er i hovedsak bygget på en samling pitesamiske ord fra prosjektet «Insamling av pitesamiska ord» (2008-2012; Nils-Henrik Bengtsson, Marianne Eriksson, Inger Fjällås, Eva-Karin Rosenberg, Gry Helen Sivertsen, Valborg Sjaggo, Dagny Skaile & Peter Steggo) med tillegg fra og omfattende redigert av Joshua Wilbur. En stor takk til Olve Utne og Peter Steggo for mange ekstra rettelser og tillegg.
sje-sjelex-links-0 = Pitesamisk ordbok
sje-online-speller = Pitesamisk stavekontroll på nett
sje-online-speller-description = Nettstavekontroll for pitesamisk: lim inn teksten din og få den rettet.
sje-online-speller-links-0 = Pitesamisk nettstavekontroll
