nds-sje = Pitesamisk NDS
nds-sje-description = Pitesamiske ordboksressurser
nds-sje-more-info = Pitesamisk nähttadigibáhko (NDS). Ordbøker mellom pitesamisk og andre språk og motsatt.
nds-sje-links-0 = Pitesamisk NDS
sjelex = Pitesamisk ordbok
sjelex-description = Pitesamisk leksikalsk database
sjelex-more-info = Den pitesamiske leksikalske databasen på nett er i hovedsak bygget på en samling pitesamiske ord fra prosjektet «Insamling av pitesamiska ord» (2008-2012; Nils-Henrik Bengtsson, Marianne Eriksson, Inger Fjällås, Eva-Karin Rosenberg, Gry Helen Sivertsen, Valborg Sjaggo, Dagny Skaile & Peter Steggo) med tillegg fra og omfattende redigert av Joshua Wilbur. En stor takk til Olve Utne og Peter Steggo for mange ekstra rettelser og tillegg.
sjelex-links-0 = Pitesamisk ordbok
sje-online-speller = Pitesamisk stavekontroll på nett
sje-online-speller-description = Nettstavekontroll for pitesamisk: lim inn teksten din og få den rettet.
sje-online-speller-links-0 = Pitesamisk nettstavekontroll
