nds-sma = Sørsamisk NDS
nds-sma-description = Sørsamiske ordboksressurser
nds-sma-more-info = Sørsamisk nedtedigibaakoe (NDS). Ordbøker mellom sørsamisk og andre språk og motsatt.
nds-sma-links-0 = Sørsamisk NDS
sma-korp = Sørsamisk Korp
sma-korp-description = Sørsamisk Korp inneholder en søkbar sørsamisk tekstsamling. Tekstene er merket med grammatisk analyse.
sma-korp-links-0 = Sørsamisk Korp
sma-oahpa = Oahpa for sørsamisk
sma-oahpa-description = Lær deg sørsamisk gjennom bruk av mange ulike øvelser.
sma-oahpa-links-0 = Åarjel-Oahpa
sma-gielese = Gïelese
sma-gielese-description = Sørsamisk begynneropplæring
sma-gielese-more-info = Gïelese er en webapp for nybegynnere, og inneholder ulike øvelser for å trene ordforråd og dagligdagse uttrykk.
sma-gielese-links-0 = Gïelese
sma-online-speller = Sørsamisk stavekontroll på nett
sma-online-speller-description = Nettstavekontroll for sørsamisk: lim inn teksten din og få den rettet.
sma-online-speller-links-0 = Sørsamisk nettstavekontroll
