sme-nds-nob = NDS for nordsamisk ⇔ bokmål
sme-nds-nob-description = Neahttadigisánit — nettordboken mellom nordsamisk og bokmål
sme-nds-nob-more-info = NDS — Neahttadigisánit — for nordsamisk og bokmål inneholder rundt 33 000 oppslagsord i begge retninger.
sme-nds-nob-links-0 = NDS Nordsamisk Bokmål
sme-nds-fin = NDS for nordsamisk ⇔ finsk
sme-nds-fin-description = Neahttadigisánit — nettordboken mellom nordsamisk og finsk
sme-nds-fin-more-info = NDS — Neahttadigisánit — for  nordsamisk og finsk inneholder rundt 11 000 oppslagsord i begge retninger.
sme-nds-fin-links-0 = NDS Nordsamisk Finsk
sme-nds-smn = NDS for nordsamisk ⇔ enaresamisk
sme-nds-smn-description = Neahttadigisánit — nettordboken mellom nordsamisk og enaresamisk
sme-nds-smn-more-info = NDS — Neahttadigisánit — for  nordsamisk og enaresamisk inneholder oversettelser i begge retninger.
sme-nds-smn-links-0 = NDS for nordsamisk - inarisamisk
sme-nds-spa = NDS for nordsamisk ⇐ spansk
sme-nds-spa-description = Neahttadigisánit — nettordboken fra spansk til nordsamisk
sme-nds-spa-more-info = NDS — Neahttadigisánit — fra spansk til nordsamisk inneholder oversettelser kun i én retning inntil videre.
sme-nds-spa-links-0 = NDS Spansk Nordsamisk
sme-jounivest = Jouni A Vest: finsk - nordsamisk ordbok
sme-jounivest-description = Nettordbok mellom nordsamisk og finsk
sme-korp = Nordsamisk Korp
sme-korp-description = Nordsamisk Korp inneholder en søkbar nordsamisk tekstsamling. Tekstene er merket med grammatisk analyse.
sme-korp-links-0 = Nordsamisk Korp
