sme-nds-nob = NDS for nordsamisk ⇔ bokmål
sme-nds-nob-description = Neahttadigisánit — nettordboken mellom nordsamisk og bokmål
sme-nds-nob-more-info = NDS — Neahttadigisánit — for nordsamisk og bokmål inneholder rundt 33 000 oppslagsord i begge retninger.
sme-nds-nob-links-0 = NDS Nordsamisk Bokmål
sme-nds-fin = NDS for nordsamisk ⇔ finsk
sme-nds-fin-description = Neahttadigisánit — nettordboken mellom nordsamisk og finsk
sme-nds-fin-more-info = NDS — Neahttadigisánit — for  nordsamisk og finsk inneholder rundt 11 000 oppslagsord i begge retninger.
sme-nds-fin-links-0 = NDS Nordsamisk Finsk
sme-nds-smn = NDS for nordsamisk ⇔ enaresamisk
sme-nds-smn-description = Neahttadigisánit — nettordboken mellom nordsamisk og enaresamisk
sme-nds-smn-more-info = NDS — Neahttadigisánit — for  nordsamisk og enaresamisk inneholder oversettelser i begge retninger.
sme-nds-smn-links-0 = NDS for nordsamisk - inarisamisk
sme-nds-spa = NDS for nordsamisk ⇐ spansk
sme-nds-spa-description = Neahttadigisánit — nettordboken fra spansk til nordsamisk
sme-nds-spa-more-info = NDS — Neahttadigisánit — fra spansk til nordsamisk inneholder oversettelser kun i én retning inntil videre.
sme-nds-spa-links-0 = NDS Spansk Nordsamisk
sme-jounivest = Jouni A Vest: finsk - nordsamisk ordbok
sme-jounivest-description = Nettordbok mellom nordsamisk og finsk
sme-jounivest-more-info = Enkel HTML-ordbok fra finsk til nordsamisk. Innholdet er alt på ei side, og du søker med søkefunksjonen i nettleseren din.
sme-jounivest-links-0 = Jouni Vest Suomi Saame
sme-juridisk = Juridisk termliste
sme-juridisk-description = Liste på nett med juridiske termer på nordsamisk, bokmål og finsk.
sme-juridisk-more-info = Enkelt søkegrensesnitt for ei liste med ca 1600 juridiske termer.
sme-juridisk-links-0 = Justermer
sme-korp = Nordsamisk Korp
sme-korp-description = Nordsamisk Korp inneholder en søkbar nordsamisk tekstsamling. Tekstene er merket med grammatisk analyse.
sme-korp-links-0 = Nordsamisk Korp
sme-oahpa = Oahpa for nordsamisk
sme-oahpa-description = Lær deg nordsamisk med mange ulike øvelser.
sme-oahpa-links-0 = Oahpa Davvi
mtsme = Maskinoversettelse for nordsamisk
mtsme-description = Maskinoversettelse fra nordsamisk til bokmål, med hjelp av Apertium. Resultatet kan bli grammatisk forbedret av ChatGPT, med risiko for at innholdet endres.
mtsme-links-0 = MT for nordsamisk
sme-online-speller = Nordsamisk stavekontroll på nett
sme-online-speller-description = Nettstavekontroll for nordsamisk: lim inn teksten din og få den retta.
sme-online-speller-links-0 = Nordsamisk nettstavekontroll
