sje-nds = NDS för pitesamiska
sje-nds-description = Ordboksresurser för pitesamiska
sje-nds-more-info = NDS — Nähttadigibáhko — för pitesamiska innehåller ordböcker med översättningar från och till pitesamiska
sje-nds-links-0 = NDS Bidum-sámegiella
sje-sjelex = Pitesamisk ordbok
sje-sjelex-description = Pitesamisk lexikalsk databas
sje-sjelex-more-info = Den pitesamiska lexikalska databasen på nätet är i huvudsak byggt på en samling pitesamiska ord från projektet «Insamling av pitesamiska ord» (2008-2012; Nils-Henrik Bengtsson, Marianne Eriksson, Inger Fjällås, Eva-Karin Rosenberg, Gry Helen Sivertsen, Valborg Sjaggo, Dagny Skaile & Peter Steggo) med tillägg från och omfattande redigering av Joshua Wilbur. Ett stort tack till Olve Utne och Peter Steggo för många extra korrigeringar och tillägg.
sje-sjelex-links-0 = Pitesamisk ordbok
sje-online-speller = Pitesamisk rättstavning på nätet
sje-online-speller-description = Rättstavning för pitesamiska på nätet: lim in din text och få den korrigerad.
sje-online-speller-links-0 = Pitesamisk näträttstavning
