sma-nds = NDS för sydsamiska
sma-nds-description = Ordboksresurser för sydsamiska
sma-nds-more-info = NDS — Nedtedigibaakoe — för sydsamiska innehåller ordböcker med översättningar från och till sydsamiska.
sma-nds-links-0 = NDS sydsamiska
sma-korp = Korp för sydsamiska
sma-korp-description = I Korp för sydsamiska kan du söka i sydsamiska texter. Texterna i verktyget är grammatiskt annoterade.
sma-korp-links-0 = Korp för sydsamiska
sma-oahpa = Oahpa för sydsamiska
sma-oahpa-description = Lär dig sydsamiska med hjälp utav olika övningar
sma-oahpa-links-0 = Åarjel-Oahpa
sma-gielese = Gïelese
sma-gielese-description = Sydsamisk språkkurs för nybörjare
sma-gielese-more-info = Gïelese är en webapp för nybörjare, och innehåller olika övningar för att träna ordförråd och vardagliga uttryck.
sma-gielese-links-0 = Gïelese
sma-online-speller = Sydsamisk rättstavning på nätet
sma-online-speller-description = Rättstavning för sydsamiska på nätet: lim in din text och få den korrigerad.
sma-online-speller-links-0 = Sydsamisk näträttstavning
