sme-nds-nob = NDS för nordsamiska ⇔ norsk bokmål
sme-nds-nob-description = Neahttadigisánit — nätordboken mellan nordsamiska och norska bokmål
sme-nds-nob-more-info = NDS — Neahttadigisánit — för nordsamiska och norska bokmål innehåller ca 33 000 uppslagsord i båda riktningarna.
sme-nds-nob-links-0 = NDS Davvi Dáru
sme-nds-fin = NDS för nordsamiska ⇔ finska
sme-nds-fin-description = Neahttadigisánit — nätordboken mellan nordsamiska och finska
sme-nds-fin-more-info = NDS — Neahttadigisánit — för nordsamiska och finska innehåller ca 11 000 uppslagsord i båda riktningarna.
sme-nds-fin-links-0 = NDS Davvi Suopma
sme-nds-smn = NDS för nordsamiska ⇔ enaresamiska
sme-nds-smn-description = Neahttadigisánit — nätordboken mellan nordsamiska och enaresamiska
sme-nds-smn-more-info = NDS — Neahttadigisánit — för nordsamiska och enaresamiska innehåller översättningar i båda riktningarna.
sme-nds-smn-links-0 = NDS Davvi Anár
sme-nds-spa = NDS för nordsamiska ⇐ spanska
sme-nds-spa-description = Neahttadigisánit — nätordboken från spanska till nordsamiska
sme-nds-spa-more-info = NDS — Neahttadigisánit — från spanska till nordsamiska innehåller översättningar i bara en riktning tills vidare.
sme-nds-spa-links-0 = NDS Spánska Davvi
sme-jounivest = Jouni A Vest: Suomi–Saame
sme-jounivest-description = Nätordbok mellan nordsamiska och finska
sme-jounivest-more-info = Enkel HTML-ordbok från finska till nordsamiska. Innehållet är allt på en sida, och du söker med sökfunktionen i din browser.
sme-jounivest-links-0 = Jouni Vest Suomi Saame
sme-juridisk = Juridisk termlista
sme-juridisk-description = Lista på nätet med juridiska termar på nordsamiska, norskt bokmål och finska.
sme-juridisk-more-info = Enkelt sökgränssnitt för en lista med ca 1600 juridiska termar.
sme-juridisk-links-0 = Justermar
sme-korp = Korp för nordsamiska
sme-korp-description = I Korp för nordsamiska kan du söka i nordsamiska texter. Texterna i verktyget är grammatiskt annoterade.
sme-korp-links-0 = Korp för nordsamiska
sme-oahpa = Oahpa för nordsamiska
sme-oahpa-description = Lär dig nordsamiska med hjälp utav olika övningar
sme-oahpa-links-0 = Oahpa Davvi
mtsme = Maskinöversättning för nordsamiska
mtsme-description = Maskinöversättning från nordsamiska till norsk bokmål, med hjälp utav Apertium. Utmatningen kan bli efterhandskorrigerad av ChatGPT, med risken för att innebörden ändras.
mtsme-links-0 = MT för nordsamiska
sme-online-speller = Nordsamisk rättstavning på nätet
sme-online-speller-description = Rättstavning för nordsamiska på nätet: lim in din text och få den korrigerad.
sme-online-speller-links-0 = Nordsamisk näträttstavning
