sme-nds-nob = Davvisámi ⇔ girjedáro NDS
sme-nds-nob-description = Neahttadigisánit sátnegirji davvisámegiela ja girjedárogiela gaskkas.
sme-nds-nob-more-info = NDS — Neahttadigisánit — davvisámegiela ja girjedárogiela gaskkas sisttisdoallá sullii 33 000 ohcansáni goabbá ge guvlui.
sme-nds-nob-links-0 = NDS Davvi Dáru
sme-nds-fin = Davvisámi ⇔ suoma NDS
sme-nds-fin-description = Neahttadigisánit sátnegirji davvisámegiela ja suomagiela gaskkas.
sme-nds-fin-more-info = NDS — Neahttadigisánit — davvisámegiela ja suomagiela gaskkas sisttisdoallá sullii 11 000 ohcansáni goabbá ge guvlui.
sme-nds-fin-links-0 = NDS Davvi Suopma
sme-nds-smn = Davvisámi ⇔ anárašgiela NDS
sme-nds-smn-description = Neahttadigisánit sátnegirji davvisámegiela ja anárašgiela gaskkas.
sme-nds-smn-more-info = NDS — Neahttadigisánit — davvisámegiela ja anárašgiela gaskkas sisttisdoallá jorgalusat goabbá ge guvlui.
sme-nds-smn-links-0 = NDS Davvi Anár
sme-nds-spa = Davvisámi ⇔ spánskka NDS
sme-nds-spa-description = Neahttadigisánit sátnegirji spánskkagielas davvisámegillii.
sme-nds-spa-more-info = NDS — Neahttadigisánit — spánskkagielas davvisámegillii sisttisdoallá jorgalusat dušše ovtta guvlui dán rádjái.
sme-nds-spa-links-0 = NDS Spánska Davvi
sme-jounivest = Jouni A Vest: Suoma–Davvisámi
sme-jounivest-description = Online sátnegirji davvisámegiela ja suomagiela gaskkas
sme-jounivest-more-info = Buiga HTML-sátnegirji suomagielas davvisámegillii. Sisdoallu lea ovtta siiddus, ja ozat neahttalogana ohcanfunkšuvnnain.
sme-jounivest-links-0 = Jouni Vest suoma – davvisámi
sme-jounivest-smefin = Jouni A Vest: Sámi–Suoma
sme-jounivest-smefin-description = Online sátnegirji davvisámegiela ja suomagiela gaskkas
sme-jounivest-smefin-more-info = Buiga HTML-sátnegirji davvisámegielas suomagillii. Sisdoallu lea ovtta siiddus, ja ozat neahttalogana ohcanfunkšuvnnain.
sme-jounivest-smefin-links-0 = Jouni A Vest: Sámi Suoma
sme-juridisk = Juridihkalaš tearbmalistu
sme-juridisk-description = Online listu mas leat juridihkalaš tearpmat davvisámi-, dáro- ja suomagiela gaskkas.
sme-juridisk-more-info = Oktageardanis ohcanlákta juridihkalaš tearbmalistui, sullii 1600 tearbmaartihkala.
sme-juridisk-links-0 = Juridihkalaš tearpmat
sme-korp = Davvisámi Korp
sme-korp-description = Davvisámi Korp lea ozahahtti davvisámi teakstačoakkáldat. Teavsttat leat grammatihkalaččat merkejuvvon.
sme-korp-links-0 = Davvisámi Korp
sme-oahpa = Davvisámi Oahpa!
sme-oahpa-description = Oahpa davvisámegiela moanaid hárjehallamiid bokte.
sme-oahpa-links-0 = Oahpa! davvi
sme-mt = Másenjorgaleapmi davvisámegielas dárogillii
sme-mt-description = Másenjorgaleapmi davvisámegielas girjedárogillii Apertium bokte. Eavttolaččat sáhttá čábbodit jorgalusaid ChatGTP:n, várra lea ahte sisdoallu rievdaduvvo.
sme-mt-links-0 = Davvisámi mášenjorgaleapmi
sme-online-speller = Davvisámi online čállindárkkisteaddji
sme-online-speller-description = Online davvisámi čállindárkkisteaddji: liibmes sisa teavstta, de oainnát čállinmeattáhusaid.
sme-online-speller-links-0 = Davvisámi  online čállindárkkisteaddji
sme-googlemt = Google másenjorgaleapmi davvisámegielas dárogillii
sme-googlemt-description = Másenjorgaleapmi sámegielas ja sámegillii, maid Google buvttada
sme-googlemt-links-0 = Google davvisámi mášenjorgaleapmi
