nds-sme = Davvisámi neahttadigisánit
nds-sme-description = Davvisámi sátnegirjeresurssat
nds-sme-more-info = Davvisámi neahttadigisánit (NDS). Sátnegirjjt davvisámi ja eará gielaid gaskkas ja nubbe lahkai.
nds-sme-links-0 = NDS Davvi
sme-korp = Davvisámi Korp
sme-korp-description = Davvisámi Korp lea ozahahtti davvisámi teakstačoakkáldat. Teavsttat leat grammatihkalaččat merkejuvvon.
sme-korp-links-0 = Davvisámi Korp
sme-oahpa = Davvisámi Oahpa!
sme-oahpa-description = Oahpa davvisámegiela moanaid hárjehallamiid bokte.
sme-oahpa-links-0 = Oahpa! davvi
mtsme = Másenjorgaleapmi davvisámegielas dárogillii
mtsme-description = Másenjorgaleapmi davvisámegielas girjedárogillii Apertium bokte. Eavttolaččat sáhttá čábbodit jorgalusaid ChatGTP:n, várra lea ahte sisdoallu rievdaduvvo.
mtsme-links-0 = Davvisámi mášenjorgaleapmi
