voisit-asr = VoisIT talukennari
voisit-asr-description = Appin skilur føroyska talu og roynir – við hjálp av vitlíki – at skriva tekstin upp á skermin. Úrslitið ávirkast av, um úttalan er týðilig, um mikrofonin er hampiliga góð, og hvussu nógv óljóð er í bakgrundini. Gev tí hesum ans.
voisit-asr-links-0 = VoisIT talukenning
voisit-asr-links-1 = VoisIT
voisit-asr-links-2 = VoisIT
sprotin = Netorðabøkur á Sprotanum
sprotin-description = Føroyskar netorðabøkur
sprotin-links-0 = Sprotin
fao-korp = Tekstagrunnurin Korp
fao-korp-description = Á Tekstagrunninum Korp kanst tú leita í føroyskum tekstum. Tekstagrunnurin er málfrøðiliga markaður.
foenmsmt = Teldutýðari hjá Bing
foenmsmt-description = Ein teldutýðari frá Microsoft. Til ber at týða bæði úr føroyskum og í føroyskt.
foenmsmt-links-0 = Týð til føroyskt
foenmsmt-links-1 = Týð úr føroyskum
malradid = Orðalistar hjá Málráðnum
malradid-description = Leita í orðalistunum hjá Málráðnum
malradid-links-0 = Orðalistar hjá Málráðnum
