fao-voisit-asr = VoisIT talukennari
fao-voisit-asr-description = Appin skilur føroyska talu og roynir – við hjálp av vitlíki – at skriva tekstin upp á skermin. Úrslitið ávirkast av, um úttalan er týðilig, um mikrofonin er hampiliga góð, og hvussu nógv óljóð er í bakgrundini. Gev tí hesum ans.
fao-voisit-asr-links-0 = VoisIT talukenning
fao-voisit-asr-links-1 = VoisIT
fao-voisit-asr-links-2 = VoisIT
fao-sprotin = Netorðabøkur á Sprotanum
fao-sprotin-description = Føroyskar netorðabøkur
fao-sprotin-links-0 = Sprotin
fao-korp = Tekstagrunnurin Korp
fao-korp-description = Á Tekstagrunninum Korp kanst tú leita í føroyskum tekstum. Tekstagrunnurin er málfrøðiliga markaður.
fao-foen-ms-mt = Teldutýðari hjá Bing
fao-foen-ms-mt-description = Ein teldutýðari frá Microsoft. Til ber at týða bæði úr føroyskum og í føroyskt.
fao-foen-ms-mt-links-0 = Týð til føroyskt
fao-foen-ms-mt-links-1 = Týð úr føroyskum
fao-malradid = Orðalistar hjá Málráðnum
fao-malradid-description = Leita í orðalistunum hjá Málráðnum
fao-malradid-links-0 = Orðalistar hjá Málráðnum
