kal-martha-tts = Atuffat Martha
kal-martha-tts-description = Kalaallisut atuffat
kal-martha-tts-links-0 = Martha TTS (tuluttut)
kal-martha-tts-links-1 = Martha TTS (kalaallisut)
kal-martha-tts-links-2 = Martha TTS (qallunaatut)
kal-dictionaries = Kalaallisut Ordbogit
kal-dictionaries-description = Kalaallisut ordbogit nittartakkaniittut
kal-dictionaries-links-0 = Kalaallisut Ordbogit
kal-learngrl = Learn Greenlandic
kal-learngrl-description = Learn Greenlandic Per Langgårdimit suliaasoq.
kal-learngrl-links-0 = Learn Greenlandic
kal-online-speller = Kalaallit oqaasiinik kukkuniiaat nittartakkatigut atugassiaq
kal-online-speller-description = Kalaallit oqaasiinik kukkuniiaat nittartakkatigut atugassiaq: allatatit immiutikkit kukkuniiartillugillu.
kal-online-speller-links-0 = Kalaallit oqaasiinik kukkuniiaat nittartakkatigut atugassiaq
